### PR TITLE
Allow changing the file extraction format

### PR DESCRIPTION
**Pull request by taraskorpach**
Related to the issue [#3458825](https://www.drupal.org/project/search_api_solr/issues/3458825)

### CODE REVIEW

**Comment by mkalkbrenner** [comment]
@HajimeGit could you update your branch? I assume that this will fix the tests.

**Comment by taraskorpach** [comment]
@mkalkbrenner there are still some unrelated failures in the tests

**Comment by mkalkbrenner** [comment]
@HajimeGit I think, I fixed them now.
Wait for this run to pass: https://github.com/mkalkbrenner/search_api_solr/actions/runs/10072702953

**Comment by taraskorpach** [comment]
@mkalkbrenner the run has failed

**Comment by mkalkbrenner** [comment]
Finally: https://github.com/mkalkbrenner/search_api_solr/actions/runs/10073628602

Now you can proceed :-)

**Comment by taraskorpach** [comment]
@mkalkbrenner looks good except for d11 with solr9. There are some problems with composer dependency.

**Comment by mkalkbrenner** [comment]
I know. That's why I added additional D11 tests with reduced dependencies.

**Pull request merged**
